language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
# Test script to run
script: ./scripts/test_run.sh
deploy:
  provider: heroku
  api_key:
    secure: KF/mrp/XMMazB64r1QOI6/T8ZHBa9l9/FvK4gnHwHr/20vz9IDTqk0Gs3+J98xqtHWZRAfRl5ZDYZLHu7m3GqOZq/nhjQNCULPChLQnb3onEWPs76FS5JRAOupdZeO0qs/YBVrOB8cNdUXl0s1ltqwn4THVB+nNvuTcR1leJ5LHcfGCowW4zmxTv9/n5yxjHvHq32ns4y6AKaNgwWyx/aa6P7bWAoPma9nDYqjEWrIFQTyPVA+/kv+bbmfIybCf4aaB0sq23CKkr16ysnUknHGUX5guVN6kf5ZXveJ9lyXARgfj9+2qJnE3BZT+6cs2jxxV+iWSKbKxNgALRZekFlbh7EZlL2koy2+fRbp9JRr8ESAMwLw3Ll6SdILVz3btvt7B059kfug4ai8kTGOBz4UyP7aOGeBavyCt/VVz2XwL3DkZvm+qYFl4kacj78TNq1t87arG405vXl7XfgfONORlvcIJbyMB9q0IlrCIhcpSa2nmJAPCAM5yjrTjoMt1IINHJcge5Ix0dcNEeC7IVa0HwRJTPg3ZK1NJpyfbfyNyAHxJy+gPd5kYaNcpEGAiHwcCeTb7ab2xJTv2oz8xNL7A5N56PGRM+f0sm0zC12b+8+of3NN78MMQ859BeUlENVmpWWea63lW3o8rzfb6wzx2ZpWsDG4cLXneiwsjjOa4=
  app: cryptic-brushlands-8563
  on:
    repo: edx/xsy
